### ISSUE TITLE
Please add tests

### ISSUE THREAD

**Issue by michalsanger** [nglgzz/kiwi-t9#1]
Hi Angelo - thanks for submitting your solution. Before I can start actually checking it I miss one important thing: unit tests of the server-side logic.

Can you please add them so we are sure you know how to write these tests? Also, think about how would you test client code if requested.

**Comment by nglgzz** [comment]
Hey @michalsanger - there's not much logic on the server side, it's literally just getting suggestions from an object, where the digit sequence is the key and the suggestions are the values.

There are tests for the client side though, they're on the `client/__test__` folder. I forgot to update the readme, will do that now. 

Let me know if that works for you or if you'd still prefer tests on the server side.

**Comment by michalsanger** [comment]
@nglgzz thanks for info about FE tests.

Having no tests on the server without any explanation could also make us think the server is untestable. Let me know if you really think no tests are needed here so we can start to review the task.

**Comment by nglgzz** [comment]
I'll write some tests to make sure that the responses from the suggestions endpoint use the right format, and that it returns the right error codes when it should. Other than that, there really isn't much to test there.

I'll update you when I'm done.

**Comment by nglgzz** [comment]
Okay API tests are up! 

Let me know if you need anything else.
